version: "3.8"
services:
  notipy:
    image: notipy:latest
    build: .
    ports:
      - 9000:9000
    secrets:
      - cert
      - key
      - vapid_key_txt
      - vapid_public_key_txt

secrets:
  cert:
    external: true
  key:
    external: true
  vapid_key_txt:
    external: true
  vapid_public_key_txt:
    external: true
